### ISSUE TITLE
Error - Decoding

### ISSUE THREAD

**Issue by beccsjb** [Mosibi/Midea-heat-pump-ESPHome#1]
G'day Richard, awesome work and i was super pleased to see that you'd refined it even more since its inception.

Curious, have you done much with the error reporting? It appears that the heatpumps have a vary array of E, H, P & F Fault codes, yet via RS485 it only outputs a single digit. 
I've seen a few random E8's on the Baxi screen and looking at history the RS485 interface is reporting an error code of 9.

**Comment by Mosibi** [comment]
Hi,

nope, I did not dive into the error codes yet. It is in the back of my head to work on sometimes. But a pull request is very welcome! ☺️

**Comment by Mosibi** [comment]
Hi @beccsjb,

I have just committed an update to heatpump.yaml where the faults (current, 1, 2 and 3) are mapped to an error code. For the current fault, I also created an extra mapping with the error description.

![image](https://github.com/Mosibi/Midea-heat-pump-ESPHome/assets/3126211/e57a4db3-685c-4385-9cf6-ea6de3118aba)
