### ISSUE TITLE
Cascade setup

### ISSUE THREAD

**Issue by mauricepot** [Mosibi/Midea-heat-pump-ESPHome#15]
Hi,

Can i also read the valeus of a cascade setup ? (more then one monoblock)
See setup example from midea. We have several customers with Dual cascade setup.
See attachment
[Midea Cascade.pdf](https://github.com/Mosibi/Midea-heat-pump-ESPHome/files/13954747/Midea.Cascade.pdf)

**Comment by Mosibi** [comment]
Hi Maurice,

In theorie yes, but as a simple home owner with only one Airwell heat pump, this is not something that I can test :) modbus_controller is a list where each controller entity has an id (name), and all entities reference that id. So you should be able to duplicate the whole set for each heat pump, but it would not surprise me when you hit a limit with to many entries at a certain point.

groet’n !
