### ISSUE TITLE
publish to mqtt

### ISSUE THREAD

**Issue by alexswart** [Mosibi/Midea-heat-pump-ESPHome#16]
Hello,

is it also possible to publish the sensor data to mqtt?
i would like to use the dashboard from the panasonic heisamon 
 
not al the functions should work but a lot of them we can also control and read with the midea modbus connection
to get an idee what topics are used for the panasonic you can take a look at 

https://github.com/Egyras/HeishaMon/blob/master/MQTT-Topics.md

the dashboard/control of it is available at

https://github.com/edterbak/NodeRed_Heishamon_control

**Comment by Mosibi** [comment]
It is possible to publish states to MQTT, see https://esphome.io/components/mqtt.html#mqtt-publish-json-action 

But be aware that this will result in extra load, especially if you are going to publish a lot of states. If I understand the question correctly, you would like to have that dashboard, in that case it is much easier to create that (almost the same) dashboard in Home Assistant.

Having a nice dashboard is still on my wishlist, so if you create something nice, I would love to adopt it in this project.
