### ISSUE TITLE
Mono block support

### ISSUE THREAD

**Issue by bkbartk** [Mosibi/Midea-heat-pump-ESPHome#29]
Hello,

I'm in the process of acquiring a Midea hybrid monoblock heatpump.
specifically "Midea MHC-V hybride 6 kW". 
The manual doesn't mention supported models specifically. 
But is does describe how to install the device on a split-unit.

So now my question is, does is support monoblock devices as well or should I look for another solution?

**Comment by Mosibi** [comment]
It also supports monoblock devices, the modbus registers for a split or a monoblock are exactly the same. You will not be the first that use this with a monoblock 😄
