### ISSUE TITLE
Update version in heatpump.yaml and CHANGED.md

### ISSUE THREAD

**Issue by rysiulg** [Mosibi/Midea-heat-pump-ESPHome#59]
Maybe this solution will be better?
change version in homepump.yaml of line esphom->project->version
and change version in CHANGELOG.md from [Unreleased] -> [version] and add new line [Unreleased] 
these two changes after you create new Release and update this version to above two files ;)
See attachment -I've tested and it works nice ;)

[github-update_version.zip](https://github.com/user-attachments/files/17478298/github-update_version.zip)

**Comment by Mosibi** [comment]
I did not have time to look into the latest updates you’ve sent, but the version is working, so I do not completely understand why I need to change that.

the only thing I need to change is to make the git push conditional
