### ISSUE TITLE
Reset fault

### ISSUE THREAD

**Issue by Berjastein** [Mosibi/Midea-heat-pump-ESPHome#6]
Hi, i really like your project!

i have a kaisai at my summerhouse, is it possible to try to reset faults?

**Comment by Mosibi** [comment]
Hi,

As far as I know, it is not possible to reset an error/fault code. If the heat pump shows an error, then the error is present. Last week I had to power off my internal unit for maintenance and that triggered error code E8, and after powering on the unit, that error was cleared.
